name: Deploy Supabase Edge Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Deploy function `pos-graphql`
        run: supabase functions deploy pos-graphql --project-ref $SUPABASE_PROJECT_REF
